### ISSUE TITLE
Include link to singularity module

### ISSUE THREAD

**Issue by bregnery** [hsf-training/hsf-training-docker#12]
I received a number of requests for a lesson teaching students how to use run singularity containers of docker images on a batch system. This should be a place to start: https://batchdocs.web.cern.ch/containers/index.html

**Comment by amanmdesai** [comment]
Hi @michmx, 
 I think this issue is resolved with https://hsf-training.github.io/hsf-training-singularity-webpage/01-introduction/index.html ?

**Comment by michmx** [comment]
Yes, you are right @amanmdesai. 
Before closing the issue, we can include a link to the new Singularity module from this one.

**Comment by amanmdesai** [comment]
Yes that would be helpful I believe.

**Comment by amanmdesai** [comment]
This issue is now resolved.

[LINK](https://hsf-training.github.io/hsf-training-docker/01-introduction/index.html#:~:text=up%20to%20run.-,Singularity,-Docker%20is%20the)
