### ISSUE TITLE
Migrate to using GitHub Actions and Deployments

### ISSUE THREAD

**Issue by matthewfeickert** [hsf-training/hsf-training-docker#13]
At the moment the default branch is `gh-pages` so that merged changes actually get deployed. This requires a _lot_ more files and structure then is necessary, which makes it harder to contribute. As deployments have gotten _significantly_ easier in the last year with the growing GitHub Actions marketplace it makes more sense to:

* Drop Travis CI in favor of GitHub Actions workflows
* Have `master` be the default branch with deployments done by CI to `gh-pages` (really view the website as a "built" product)
* Remove all the unnecessary files that are generated at build time and keep a much simpler directory structure

**Comment by klieret** [comment]
Hi @matthewfeickert . 

> This requires a lot more files and structure then is necessary, which makes it harder to contribute. 

What would be concrete examples of this? 

> Have master be the default branch with deployments done by CI to gh-pages

I also don't really understand what you mean with "deploying to a branch". Would that mean that ``gh-pages`` would be a branch that has only HTML files built from what is at ``master``? Why would that make anything easier? 

> Remove all the unnecessary files that are generated at build time and keep a much simpler directory structure

Again I'm confused, because this repository doesn't contain anything that's generated at build time.

**Comment by klieret** [comment]
The only thing I could see is the ``bin``, ``code``, ``fig``, .. folder, but that's a remnant from how this repository is being initialized and kept in sync with the template at https://github.com/hsf-training/hsf-styles which is based on the carpentry version of it, https://github.com/carpentries/styles.

I would generally be wary of any larger changes that make us diverge from the carpentry setup.

**Comment by klieret** [comment]
Ah, I see what you mean now. Like what LHCb does for their starterkit repository...

**Comment by klieret** [comment]
Let me link some related discussion from the carpentries world:

* https://github.com/carpentries/styles/issues/287
* https://github.com/carpentries/styles/issues/456
* https://github.com/carpentries/lesson-infrastructure/issues/16

**Comment by klieret** [comment]
We are in the progress to switching over to using [our theme](https://github.com/hsf-training/hsf-training-theme), which will solve most of this.
