### ISSUE TITLE
Bonus content ideas

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-docker#15]
As mentioned in the debrief:

* Containerization in distributed systems:
  * How to submit to a batch system...
* Make dockerhub into a full episode

**Comment by michmx** [comment]
> As mentioned in the debrief:
> * Containerization in distributed systems:  
>   * How to submit to a batch system...

I am thinking about this one and running Docker in a batch system is not straightforward. Actually, it is one of the motivations why Singularity/Apptainer exists. I would not add it as a bonus topic, since in most of the large sites Docker will not be available (Singularity is).

**Comment by klieret** [comment]
Then I will close this, as the thing with dockerhub seems to be only a small improvement and we have many issues open already
