### ISSUE TITLE
Add Glossary

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-docker#25]
Here: https://hsf-training.github.io/hsf-training-docker/reference.html

**Comment by klieret** [comment]
...or simply delete it

**Comment by amanmdesai** [comment]
I was thinking to do something similar to what you suggested in [link](https://github.com/hsf-training/hsf-training-matplotlib/issues/105).

put a docker cheat sheet? what is your opinion, will it be helpful?

I came across this sheet for example: https://www.docker.com/wp-content/uploads/2022/03/docker-cheat-sheet.pdf

**Comment by klieret** [comment]
I think this would be a nice addition to the lesson. It's not exactly a glossary though... One could explain container vs image vs .... etc. here though

**Comment by amanmdesai** [comment]
yeah.

**Comment by amanmdesai** [comment]
@klieret  shall we close this issue and associated PR #47 with the latest PR #50

**Comment by klieret** [comment]
Yes, let's close this. Thank you again for updating the keypoints!
