### ISSUE TITLE
update keypoints

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-docker#48]
<details>
<summary><strong>Instructions</strong></summary>

Thanks for contributing! :heart:

If this issue is about a specific episode within a lesson, please provide its link or filename.

Keep in mind that **lesson maintainers are volunteers** and it may take them some time to respond to your contribution.
To ensure that the right people get notified, you can tag some of the last contributors with `@githubname`.

Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum. If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact the HSF training convenors ([contacts here](https://hepsoftwarefoundation.org/workinggroups/training.html)).

You may delete these instructions from your issue.

\- HSF Training
</details>

**Comment by michmx** [comment]
Hi @amanmdesai . Thanks for opening the issue!  Could you elaborate a bit more on which keypoints do you consider must be updated?

**Comment by amanmdesai** [comment]
Hi @michmx, updates would be following the discussions here: #25  and #47

my original idea was to include a cheatsheet like page so that anyone could look at that and carry out the important steps, see for instance here: https://github.com/hsf-training/hsf-training-docker/pull/47/files
