### ISSUE TITLE
Move CI/CD content from Docker to github/gitlab CI/CD

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-docker#65]

**Comment by GuillermoFidalgo** [comment]
This would mainly move ep8&ep9 -> [Gitlab CI/CD](https://hsf-training.github.io/hsf-training-cicd/)

**Comment by GuillermoFidalgo** [comment]
made the PR on the Gitlab edition

**Comment by GuillermoFidalgo** [comment]
Can we close this issue and move on to #70 ?

**Comment by klieret** [comment]
Sounds good to me!
